### ISSUE TITLE
how the heck do i run this

### ISSUE THREAD

**Issue by hens50** [DidierRLopes/GiveawayNFTbot#2]
I know how to at least upload the folder to vs code but what tf do i do from there. I have the config all set up but otherwise im stuck. Please and thanks.

**Comment by DidierRLopes** [comment]
Hey @heregoesnothing3d,

You can open the terminal window on VS Code and make sure you are on the directory "GiveawayNFTbot" and then if all the API keys are filled in you can run with:

```
python giveaway_nft_bot.py
```

**Comment by DidierRLopes** [comment]
Let me know if that works.

**Comment by hens50** [comment]
Wooooo!! It took until like 2 am last night but I got it. Heres another quick question -- is there a way to disable auto opening chrome to the page of the giveaway NFT? Thanks

**Comment by DidierRLopes** [comment]
> Wooooo!! It took until like 2 am last night but I got it. Heres another quick question -- is there a way to disable auto opening chrome to the page of the giveaway NFT? Thanks

Nice!

Yes there is, comment line 113. I.e. add a `#` right before it:

![image](https://user-images.githubusercontent.com/25267873/159369830-a3f63778-0607-4d11-8b0a-897bec301651.png)

**Comment by hens50** [comment]
Ahhhhh thanks

**Comment by DidierRLopes** [comment]
> Ahhhhh thanks

Happy to help! Hope you get some nice NFTs 😄
